apiVersion: apps/v1
kind: Deployment
metadata:
  name: photoidentify-deployment
  labels:
    app: photoidentify
spec:
  selector:
    matchLabels:
      app: photoidentify
  template:
    metadata:
      labels:
        app: photoidentify
    spec:
      containers:
        - name: photoidentify-container
          image: 247522201286.dkr.ecr.us-east-1.amazonaws.com/awsguide/photoidentify:1.0-SNAPSHOT
          ports:
            - containerPort: 9080
---
apiVersion: v1
kind: Service
metadata:
  name: photoidentify-service
spec:
  type: NodePort
  selector:
    app: photoidentify
  ports:
    - protocol: TCP
      port: 9080
      targetPort: 9080
      nodePort: 32600
